declare module 'react-icons/fa' {
  import { ComponentType } from 'react';
  
  interface IconProps {
    className?: string;
    size?: string | number;
    color?: string;
    title?: string;
  }
  
  export const FaBars: ComponentType<IconProps>;
  export const FaBell: ComponentType<IconProps>;
  export const FaUser: ComponentType<IconProps>;
  export const FaCog: ComponentType<IconProps>;
  export const FaSignOutAlt: ComponentType<IconProps>;
  export const FaTimes: ComponentType<IconProps>;
  export const FaHome: ComponentType<IconProps>;
  export const FaCloud: ComponentType<IconProps>;
  export const FaCreditCard: ComponentType<IconProps>;
  export const FaChartBar: ComponentType<IconProps>;
  export const FaUpload: ComponentType<IconProps>;
  export const FaShieldAlt: ComponentType<IconProps>;
  export const FaFileInvoiceDollar: ComponentType<IconProps>;
  export const FaLock: ComponentType<IconProps>;
  export const FaEye: ComponentType<IconProps>;
  export const FaEyeSlash: ComponentType<IconProps>;
  export const FaEnvelope: ComponentType<IconProps>;
  export const FaPhone: ComponentType<IconProps>;
  export const FaBuilding: ComponentType<IconProps>;
  export const FaBriefcase: ComponentType<IconProps>;
  export const FaCheck: ComponentType<IconProps>;
  export const FaExclamationTriangle: ComponentType<IconProps>;
  export const FaCloudUploadAlt: ComponentType<IconProps>;
  export const FaFileImage: ComponentType<IconProps>;
  export const FaPlus: ComponentType<IconProps>;
  export const FaSave: ComponentType<IconProps>;
  export const FaEdit: ComponentType<IconProps>;
  export const FaUsers: ComponentType<IconProps>;
  export const FaUserCheck: ComponentType<IconProps>;
  export const FaUserTimes: ComponentType<IconProps>;
  export const FaCrown: ComponentType<IconProps>;
  export const FaStar: ComponentType<IconProps>;
  export const FaArrowLeft: ComponentType<IconProps>; 
  export const FaArrowRight: ComponentType<IconProps>;
  export const FaArrowUp: ComponentType<IconProps>;
  export const FaArrowDown: ComponentType<IconProps>;
  export const FaArrowLeft: ComponentType<IconProps>;
  export const FaArrowRight: ComponentType<IconProps>;
  export const FaArrowUp: ComponentType<IconProps>;
  export const FaArrowDown: ComponentType<IconProps>;
  export const FaArrowLeft: ComponentType<IconProps>;
  export const FaArrowRight: ComponentType<IconProps>;
  export const FaArrowUp: ComponentType<IconProps>;
  export const FaArrowDown: ComponentType<IconProps>;
  export const FaHeart: ComponentType<IconProps>;
  export const FaAmazon: ComponentType<IconProps>;
  export const FaDollarSign: ComponentType<IconProps>;
  export const FaInfoCircle: ComponentType<IconProps>;
  export const FaQuestionCircle: ComponentType<IconProps>;
  export const FaExternalLinkAlt: ComponentType<IconProps>;
  export const FaRedoAlt: ComponentType<IconProps>;
  export const FaSpinner: ComponentType<IconProps>;
  export const FaCamera: ComponentType<IconProps>;
  export const FaSearch: ComponentType<IconProps>;
  export const FaFilter: ComponentType<IconProps>;
  export const FaTrash: ComponentType<IconProps>;
  export const FaCalendarAlt: ComponentType<IconProps>;
  export const FaImages: ComponentType<IconProps>;
  export const FaQrcode: ComponentType<IconProps>;
  export const FaShare: ComponentType<IconProps>;
  export const FaMapMarkerAlt: ComponentType<IconProps>;
  export const FaChartLine: ComponentType<IconProps>;
  export const FaDownload: ComponentType<IconProps>;
  export const FaPrint: ComponentType<IconProps>;
  export const FaCopy: ComponentType<IconProps>;
  export const FaBarcode: ComponentType<IconProps>;
  export const FaVideo: ComponentType<IconProps>;
  export const FaPlay: ComponentType<IconProps>;
  export const FaPlayCircle: ComponentType<IconProps>;
  export const FaFolder: ComponentType<IconProps>;
  export const FaFolderOpen: ComponentType<IconProps>;
  export const FaChevronLeft: ComponentType<IconProps>;
  export const FaChevronRight: ComponentType<IconProps>;
  export const FaPalette: ComponentType<IconProps>;
  export const FaGlobe: ComponentType<IconProps>;
  export const FaKey: ComponentType<IconProps>;
  export const FaTree: ComponentType<IconProps>;
  export const FaSitemap: ComponentType<IconProps>;
  export const FaUserPlus: ComponentType<IconProps>;
  export const FaCheckCircle: ComponentType<IconProps>;
  export const FaUserFriends: ComponentType<IconProps>;
  export const FaRupeeSign: ComponentType<IconProps>;
  export const FaClock: ComponentType<IconProps>;
  export const FaUserTag: ComponentType<IconProps>;
  export const FaImage: ComponentType<IconProps>;
  export const FaBook: ComponentType<IconProps>;
  export const MdIcon: ComponentType<IconProps & { icon?: string }>;
  export const FaExpand: ComponentType<IconProps>;
  export const FaExpandArrowsAlt: ComponentType<IconProps>;
  export const FaFlag: ComponentType<IconProps>;
  export const FaGripVertical: ComponentType<IconProps>;
  export const FaGripHorizontal: ComponentType<IconProps>;
  export const FaShareAlt: ComponentType<IconProps>;
  export const FaBookOpen: ComponentType<IconProps>;
  export const FaRobot: ComponentType<IconProps>;
  export const FaUndo: ComponentType<IconProps>;
  export const FaUserCog: ComponentType<IconProps>;
  export const FaSlidersH: ComponentType<IconProps>;
  export const FaComments: ComponentType<IconProps>;
  export const FaMicrophone: ComponentType<IconProps>;
  export const FaPaperPlane: ComponentType<IconProps>;
  export const FaRedo: ComponentType<IconProps>;
  export const FaVolumeUp: ComponentType<IconProps>;
  export const FaVolumeMute: ComponentType<IconProps>;
  export const FaMagic: ComponentType<IconProps>;
  export const FaMagic: ComponentType<IconProps>;
  export const FaWhatsapp: ComponentType<IconProps>;
  export const FaLink: ComponentType<IconProps>;
  export const FaUnlink: ComponentType<IconProps>;
  export const FaSyncAlt: ComponentType<IconProps>;
  export const FaTimesCircle: ComponentType<IconProps>;
  export const FaInbox: ComponentType<IconProps>;
  export const FaCheckDouble: ComponentType<IconProps>;
  export const FaExclamationCircle: ComponentType<IconProps>;
  export const FaSync: ComponentType<IconProps>;
  export const FaLayerGroup: ComponentType<IconProps>;
  export const FaFont: ComponentType<IconProps>;
  export const FaRandom: ComponentType<IconProps>;
  export const FaLifeBuoy: ComponentType<IconProps>;
  export const FaLightbulb: ComponentType<IconProps>;
  export const FaLightbulbOn: ComponentType<IconProps>;
  export const FaLightbulbOff: ComponentType<IconProps>;
  export const FaLightbulbOnOff: ComponentType<IconProps>;
  export const FaLightbulbOnOff: ComponentType<IconProps>;

}

declare module 'react-icons/fi' {
  import { ComponentType } from 'react';
  
  interface IconProps {
    className?: string;
    size?: string | number;
    color?: string;
    title?: string;
  }
  
  export const FiDownload: ComponentType<IconProps>;
  export const FiTrash2: ComponentType<IconProps>;
}
