/** Theme tokens — aligned with Our Memories landing / login (ink & stone). */
export const THEME = {
  primary: '#141210',
  primaryLight: '#1f3a34',
  background: 'var(--sd-page-bg)',
  cardBackground: 'var(--sd-card)',
  heroBackground: 'var(--sd-hero-bg)',
  border: 'var(--sd-border)',
  textPrimary: 'var(--sd-text-primary)',
  textSecondary: 'var(--sd-text-secondary)',
  success: '#1f3a34',
  shadow: 'var(--sd-shadow-medium)',
  primaryHover: '#1f3a34',
  cardBg: 'var(--sd-card)',
  textMuted: 'var(--sd-text-muted)',
  borderLight: 'var(--sd-border-light)',
  heroGradient: 'var(--sd-hero-bg)',
  shadowLight: 'var(--sd-shadow)',
  shadowMedium: 'var(--sd-shadow-medium)',
  shadowHeavy: 'var(--sd-shadow-medium)',
  glassBg: 'var(--sd-glass)',
  glassBgLight: 'var(--sd-glass)',
  glassBgLighter: 'var(--sd-glass)',
  chartColors: ['#141210', '#1f3a34', '#5c574f', '#8a847a', '#c5c0b6'],
  online: '#1f3a34',
  offline: 'var(--sd-text-muted)',
  warning: '#8a5a2b',
  hoverOverlay: 'rgba(20,18,16,0.06)',
  activeScale: 'scale-[0.98]',
  hoverScale: 'scale-[1.02]',
  tooltipBg: 'var(--sd-tooltip-bg)',
  tooltipBorder: 'var(--sd-tooltip-border)',
  statusNewBg: 'var(--sd-status-new-bg)',
};
