/** Theme tokens — CSS variables switch in light / dark / system (see StudioDashboard.css). */
export const THEME = {
  primary: '#2563EB',
  primaryLight: '#3B82F6',
  background: 'var(--sd-page-bg)',
  cardBackground: 'var(--sd-card)',
  heroBackground: 'var(--sd-hero-bg)',
  border: 'var(--sd-border)',
  textPrimary: 'var(--sd-text-primary)',
  textSecondary: 'var(--sd-text-secondary)',
  success: '#10B981',
  shadow: 'var(--sd-shadow-medium)',
  primaryHover: '#3B82F6',
  cardBg: 'var(--sd-card)',
  textMuted: 'var(--sd-text-muted)',
  borderLight: 'var(--sd-border-light)',
  heroGradient: 'var(--sd-hero-bg)',
  shadowLight: 'var(--sd-shadow)',
  shadowMedium: 'var(--sd-shadow-medium)',
  shadowHeavy: 'var(--sd-shadow-medium)',
  glassBg: 'var(--sd-glass)',
  glassBgLight: 'var(--sd-glass)',
  glassBgLighter: 'var(--sd-glass)',
  chartColors: ['#2563EB', '#3B82F6', '#60A5FA', '#93C5FD', '#BFDBFE'],
  online: '#10B981',
  offline: 'var(--sd-text-muted)',
  warning: '#F59E0B',
  hoverOverlay: 'rgba(37,99,235,0.08)',
  activeScale: 'scale-[0.98]',
  hoverScale: 'scale-[1.02]',
  tooltipBg: 'var(--sd-tooltip-bg)',
  tooltipBorder: 'var(--sd-tooltip-border)',
  statusNewBg: 'var(--sd-status-new-bg)',
};
